import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../../public/sass/helper/helper.scss";
import "../../public/sass/helper/base.scss";
import "../../public/sass/helper/reset.scss";
import "../../public/sass/global.scss";
import Header from "./components/header";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>

      <body>
        <Header />
        <ToastContainer autoClose={1000} hideProgressBar={true} limit={1}/>
        {children}
      </body>
    </html>
  );
}
